// Generated by https://quicktype.io

export interface Respuesta {
    success:   boolean;
    proyectos: Proyecto[];
}

export interface Proyecto {
    id:                      number;
    titulo:                  string;
    estado:                  string;
    descripcion:             string;
    macro_proyecto:          number;
    fecha_inicio:            string;
    fecha_fin:               string;
    semillero:               number;
    retroalimentacion_final: string;
    visibilidad:             number;
    ciudad:                  string;
    metodologia:             string;
    conclusiones:            string;
    justificacion:           string;
    tipo_proyecto:           string;
    nombre_facultad:         string;
    nombre_programa:         string;
    participantes:           Participante[];
    area_conocimientos:      AreaConocimiento[];
}

export interface AreaConocimiento {
    id:          number;
    nombre:      string;
    gran_area:   string;
    descripcion: string;
    pivot:       Pivot;
}

export interface Pivot {
    proyecto:          number;
    area_conocimiento: number;
}

export interface Participante {
    cedula:            string;
    cod_universitario: number;
    correo_est:        string;
    nombres:           string;
    apellidos:         string;
    telefono:          string;
    correo_personal:   string;
    semillero_id:      null;
    programa_id:       number;
}
